package com.szemingcheng.amemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szemingcheng.amemo.entity.Memo;
import com.szemingcheng.amemo.entity.NoteBK;
import com.szemingcheng.amemo.entity.User;

import com.szemingcheng.amemo.dao.MemoDao;
import com.szemingcheng.amemo.dao.NoteBKDao;
import com.szemingcheng.amemo.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memoDaoConfig;
    private final DaoConfig noteBKDaoConfig;
    private final DaoConfig userDaoConfig;

    private final MemoDao memoDao;
    private final NoteBKDao noteBKDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memoDaoConfig = daoConfigMap.get(MemoDao.class).clone();
        memoDaoConfig.initIdentityScope(type);

        noteBKDaoConfig = daoConfigMap.get(NoteBKDao.class).clone();
        noteBKDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        memoDao = new MemoDao(memoDaoConfig, this);
        noteBKDao = new NoteBKDao(noteBKDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Memo.class, memoDao);
        registerDao(NoteBK.class, noteBKDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        memoDaoConfig.clearIdentityScope();
        noteBKDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public MemoDao getMemoDao() {
        return memoDao;
    }

    public NoteBKDao getNoteBKDao() {
        return noteBKDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
